name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-dev-merge-main-build-main: #this way this and merge-branch actually run in parallel

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
    - name: merge to main
    - uses: actions/checkout@v2
    - uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        source_ref: 'dev'
        target_branch: 'main'
        commit_message_template: '[Automated] merged {source_ref} into target {target_branch}'
          
    - name: build and test main
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
